### ISSUE TITLE
Multiple Cameras on the same device, selecting (manually) one [request]

### ISSUE THREAD

**Issue by Specimen** [alicevision/Meshroom#2312]
**Is your feature request related to a problem? Please describe.**
Smartphones usually have more than one camera with different sensor sizes. And I've used more than one sensor of the same device for different projects (I've used just one sensor for all photos of the same project).

As such, I have set more than one sensor for the same device in the db, Meshroom will automatically select the first it finds, I've to manually edit the db before loading the photos in order to make sure Meshroom selects the correct one.

**Describe the solution you'd like**
It would be nice to have those multiple cameras in the db, and if meshroom found more than one match (make and model) when processing the photos the user could choose which one was used (the metadata, unfortunately might not register what camera was used).

**Describe alternatives you've considered**
Editing the db file each time the sensor used for the same device is different than last time.

**Additional context**
My specific case is the Samsung Galaxy S22 5G (SM-S901B)

Here is the info of two of the rear sensors I've used, unfortunately it's not so easy to find all necessary information for all of them (if anyone wants to add to the db):

Samsung;SM-S901B;8.16;devicespecificationsS22rearwide
Samsung;SM-S901B;5.6;devicespecificationsS22rearultrawide

Thank you!

**Comment by natowi** [comment]
Thank you! This is a known issue and at the moment the main camera is added to the database.

**Comment by shanji97** [comment]
I am facing the same question. Is this something that is implemented in 2025.1? Can I add multiple entries in the sensors db for same device?

**Comment by natowi** [comment]
No, we do not have a solution for that yet. I have raised the issue, but it is tricky to solve.  So far we add the primary camera to the sensordb.  Ideas or contributions to handle this are welcome.

**Comment by shanji97** [comment]
I could make a PR for the main camera sensor of the iPhone Pro Max 16, althought I am not sure if I need to use 1/1.28 or 1/1.14 as both values are mentioned for the Sony IMX 903. Others I can  provide somewhere (where exacty?) to add them later. Comparing the telephoto and the main sensor side by side...Comparing the exif data from the images mentioned [here](https://github.com/alicevision/Meshroom/issues/2198#issuecomment-3239135272). I see the following exif data (via the [exif tool](https://sourceforge.net/projects/exiftool/)):
`Lens ID: iPhone 16 Pro Max back triple camera 15.66mm f/2.8 | iPhone 16 Pro Max back triple camera 2.22mm f/2.2 | iPhone 16 Pro Max back triple camera 6.765mm f/1.78` (also listed under Lens Model). Alternatively some other EXIF data mapping to sensor parameters could be used.
If some images cannot be linked with a used sensor, then some options could be used:
- discard uncategorized images (also a general fallback)
- assume, that the uncategorized images are part of the sensor with which the most photos were taken (or use fallback)
- manually mapping or create subfolders with easy to parse naming conventions.

**Comment by Shrinks99** [comment]
Also running into this with my iPhone.  I was going to add it to the database, but would rather not if there's no comprehensive method to cover the device's three back cameras!

After taking a look at the DB, it seems that the big limitation here is the single key/value pair between the device name and its sensor width.  For devices with a signel camera sensor that supports inter-changable lenses this makes sense, but I feel like for smartphones there's also an opportunity to encode the focal length data into the camera intrinsics?

Here's one idea represented in YAML for how this might be expanded.

```yaml
manufacturer:
  - Apple:
      - iPhone 17 pro:
          cameras:
            - Rear Main:
                focallength: 6.8
                sensorwidth: 9.76
            - Rear Ultrawide:
                focallength: 2.2
                sensorwidth: 5.6
            - Rear Telephoto:
                focallength: 16.9
                sensorwidth: 5.6
          sources:
            - usercontribution
      - iPhone xR:
          cameras:
            - Rear Main:
                focallength: 4.2
                sendsorwidth: 5.60
          sources:
            - dpreview
            - usercontribution
  - RED:
    - DRAGON-X 5K S35:
        cameras:
          - Main: 
              sensorwidth: 25.6
        sources:
            - usercontribution
```

 We could also add EXIF values that are known to match to each `camera`?  The iPhone is able to show this in the image properties, so I figure it's in here and just a matter of sorting out exactly which fields are the right ones.
